export type Phrase = {
    gibberish: string;
    actual: string;
};

export const phrases: Phrase[] = [
    { gibberish: "eye no their", actual: "i know there" },
    { gibberish: "egg sample", actual: "example" },
    { gibberish: "pace hips", actual: "spaceships" },
    { gibberish: "chalk lid mousse", actual: "chocolate mousse" },
    { gibberish: "sick sand tones", actual: "six antunes" },
    { gibberish: "eye scream yous cream", actual: "ice cream you scream" },
    { gibberish: "bee leave in me", actual: "believe in me" },
    { gibberish: "eye no won", actual: "i know one" },
    { gibberish: "so fair a weigh", actual: "so far away" },
    { gibberish: "chalk late chip cook ease", actual: "chocolate chip cookies" },
    { gibberish: "dawned go there", actual: "don’t go there" },
    { gibberish: "hive yore bake", actual: "have your back" },
    { gibberish: "thy me know", actual: "let me know" },
    { gibberish: "sin ding hey long", actual: "singing along" },
    { gibberish: "bah ten aim", actual: "bought a name" },
    { gibberish: "mine dusk reef", actual: "mind's grief" },
    { gibberish: "pea nut putter", actual: "peanut butter" },
    { gibberish: "know thing hells matters", actual: "nothing else matters" },
    { gibberish: "ache up off tea", actual: "a cup of tea" },
    { gibberish: "high duff knew", actual: "I don’t know" },
    { gibberish: "eye wheel knot go", actual: "I will not go" },
    { gibberish: "aim maze ink gray", actual: "amazing grace" },
    { gibberish: "noun daze", actual: "nowadays" },
    { gibberish: "fuzz sun boot hen", actual: "fast and furious" },
    { gibberish: "tents sun shun", actual: "attention" },
    { gibberish: "tie mere ends", actual: "timer ends" },
    { gibberish: "whale yew bee mine", actual: "will you be mine" },
    { gibberish: "honey do list", actual: "honeydew list" },
    { gibberish: "chew her hey us", actual: "jurassicus" },
    { gibberish: "aches plain", actual: "explain" },
    { gibberish: "thee fit her", actual: "the future" },
    { gibberish: "luff at thirst sight", actual: "love at first sight" },
    { gibberish: "duh fence is", actual: "defenses" },
    { gibberish: "gulf rend zone", actual: "girlfriend's home" },
    { gibberish: "hail owe win", actual: "halloween" },
    { gibberish: "fur get hub out hit", actual: "forget about it" },
    { gibberish: "oh pin yon", actual: "opinion" },
    { gibberish: "ware izzy", actual: "where is he" },
    { gibberish: "he's ache craze eon", actual: "he’s a crazy one" },
    { gibberish: "inn fence sieve", actual: "invasive" },
    { gibberish: "nighs toe meat you", actual: "nice to meet you" },
    { gibberish: "aisle bee rite bake", actual: "I'll be right back" },
    { gibberish: "knot towel aid", actual: "not too late" },
    { gibberish: "due knot bee laid", actual: "do not be late" },
    { gibberish: "bee yawn belief", actual: "beyond belief" },
    { gibberish: "bay sea callee", actual: "basically" },
    { gibberish: "hat chip true lee", actual: "actually" },
    { gibberish: "owe fern dune", actual: "over and done" },
    { gibberish: "aim broth hurt", actual: "I'm brothered" },
    { gibberish: "hour rated", actual: "outrated" },
    { gibberish: "low kin boot", actual: "looking good" },
    { gibberish: "ache hint sure", actual: "a kind gesture" },
    { gibberish: "torn heap age", actual: "turn the page" },
    { gibberish: "bee zing hair oar", actual: "bees in her hair" },
    { gibberish: "aim palm beach", actual: "I'm pumped" },
    { gibberish: "chalk lit camp pain", actual: "chocolate campaign" },
    { gibberish: "heel owe hat", actual: "hello hat" },
    { gibberish: "end chew lark", actual: "and you laugh" },
    { gibberish: "dew know whoop", actual: "do you know" },
    { gibberish: "why foe fight", actual: "wifi fight" },
    { gibberish: "bake hume eel", actual: "vacuum meal" },
    { gibberish: "miss chin ink", actual: "mission ink" },
    { gibberish: "cape on going", actual: "keep on going" },
    { gibberish: "aim moan duh", actual: "I'm on the" },
    { gibberish: "how sin ache", actual: "house and lake" },
    { gibberish: "chews thee rate", actual: "choose the right" },
    { gibberish: "sore tea purse hint", actual: "sort of persistent" },
    { gibberish: "pie rut bay", actual: "pirate bay" },
    { gibberish: "week ant cope", actual: "we can't cope" },
    { gibberish: "gaze cube aid", actual: "case you paid" },
    { gibberish: "thin gage ease", actual: "thing of geese" },
    { gibberish: "peck lure hips", actual: "peculiar lips" },
    { gibberish: "care full eye", actual: "carefully" },
    { gibberish: "hawk shun leak aim", actual: "optionally game" },
    { gibberish: "whirled weigh", actual: "world away" },
    { gibberish: "goal den moan mint", actual: "golden moment" },
    { gibberish: "add lent tick", actual: "Atlantic" },
    { gibberish: "aim bore tin", actual: "important" },
    { gibberish: "frizz bee tour", actual: "Frisbee tour" },
    { gibberish: "bait heat roll", actual: "bet he trolled" },
    { gibberish: "chick hen soup", actual: "chicken soup" },
    { gibberish: "could he whoa man", actual: "pretty woman" },
    { gibberish: "bring king nose", actual: "breaking news" },
    { gibberish: "fry risk oat", actual: "Ferris coat" },
    { gibberish: "hook din pie", actual: "hooked in pie" },
    { gibberish: "loaf sand her", actual: "loaves and her" },
    { gibberish: "toe tell eee clips", actual: "total eclipse" },
    { gibberish: "aim bass hatter", actual: "embassy chatter" },
    { gibberish: "grate aim son", actual: "great Amazon" },
    { gibberish: "wait for hit", actual: "wait for it" },
    { gibberish: "off ten lace", actual: "often less" },
    { gibberish: "hope sin oars", actual: "open doors" },
    { gibberish: "coal dust room", actual: "coldest room" },
    { gibberish: "bet her lake", actual: "better late" },
    { gibberish: "match stick mime hint", actual: "matchstick moment" },
    { gibberish: "boot her fling", actual: "butterfly wing" },
    { gibberish: "sink oar hando", actual: "Cinco de Mayo" },
    { gibberish: "pie knoll type", actual: "final type" },
    { gibberish: "know thing dough it", actual: "nothing to it" },
    { gibberish: "hat chip hay per", actual: "at your paper" },
    { gibberish: "grain moth her", actual: "grandmother" },
    { gibberish: "lie sent sense", actual: "license" },
    { gibberish: "fill his tub hurts", actual: "flicks to birds" },
    { gibberish: "trail lairs tape", actual: "trailer's tape" },
    { gibberish: "yak owes son", actual: "yeah go son" },
    { gibberish: "rack hurt ship", actual: "rocket ship" },
    { gibberish: "prick key melt", actual: "pretty milk" },
    { gibberish: "cake halves raw", actual: "kick off straw" },
    { gibberish: "seek hew lit", actual: "see you later" },
    { gibberish: "hiss thorn eel", actual: "historian" },
    { gibberish: "owe fish alley", actual: "officially" },
    { gibberish: "dye numb might", actual: "dynamite" },
    { gibberish: "aim broom hair", actual: "amber mare" },
    { gibberish: "pie rates off duh care hip bean", actual: "pirates of the Caribbean" },
    { gibberish: "too thing hen", actual: "two thinking" },
    { gibberish: "chew now", actual: "channel" },
    { gibberish: "ink wear hey bull", actual: "incredible" },
    { gibberish: "nigh grass ape", actual: "night grape escape" },
    { gibberish: "tall kin do me", actual: "talking to me" },
    { gibberish: "bee yawn hair", actual: "beyond here" },
    { gibberish: "ham merger scent see", actual: "emergency" },
    { gibberish: "sigh burr sunk", actual: "cyberpunk" },
    { gibberish: "min hiss tear he", actual: "ministry" },
    { gibberish: "aim haze ink tray", actual: "amazing trade" },
    { gibberish: "fan tuss tick", actual: "fantastic" },
    { gibberish: "miss teal tore he", actual: "mystery" },
    { gibberish: "fee newmen all", actual: "phenomenal" },
    { gibberish: "less hen dirt", actual: "less than dirt" },
    { gibberish: "air port coed", actual: "airport code" },
    { gibberish: "eye reek hunt rowl", actual: "I recon troll" },
    { gibberish: "chews them ay", actual: "choose the way" },
    { gibberish: "yule low calf", actual: "you look off" },
    { gibberish: "core rect me if I’m wrong", actual: "correct me if I'm wrong" },
    { gibberish: "eye ham stew did", actual: "I am stupid" },
    { gibberish: "off wish yell he", actual: "officially" },
    { gibberish: "hand decks plain ash in", actual: "and explanation" },
    { gibberish: "meh toe rear itch", actual: "meteorite" },
    { gibberish: "pie rate hug aim", actual: "pirate game" },
    { gibberish: "aim mad a mast ache", actual: "I made a mistake" },
    { gibberish: "fry day night", actual: "Friday night" },
    { gibberish: "wet hair youth ink", actual: "whatever you think" },
    { gibberish: "due nut leaf me", actual: "do not leave me" },
    { gibberish: "bin dare dunthat", actual: "been there done that" },
    { gibberish: "aim put tent", actual: "important" },
    { gibberish: "sum thin feels off", actual: "something feels off" },
    { gibberish: "whale gum two duh team", actual: "welcome to the team" },
    { gibberish: "new deal lease", actual: "noodles" },
    { gibberish: "aim tough fee ice", actual: "empty of the eyes" },
    { gibberish: "law sand juice found", actual: "lost and just found" },
    { gibberish: "how stair yak shin", actual: "hostel reaction" },
    { gibberish: "he’s trawl ink news", actual: "he's trolling news" },
    { gibberish: "chore jazz pink", actual: "George has pink" },
    { gibberish: "bless huff yawn", actual: "bless of yawn" },
    { gibberish: "sue pear none", actual: "super unknown" },
    { gibberish: "hiss aids sew", actual: "he said so" },
    { gibberish: "bee churn crayon", actual: "picture crying" },
    { gibberish: "stair tough aim hush in", actual: "start of a mission" },
    { gibberish: "ache rim hiss pecked", actual: "cream is perfect" },
    { gibberish: "doll lures sank tour", actual: "dollar sanctuary" },
    { gibberish: "aim hush yawn dawn", actual: "emotion down" },
    { gibberish: "nigh steam eerie", actual: "nice to meet me" },
    { gibberish: "trough all aim itch", actual: "travel image" },
    { gibberish: "awe fern hiss dish", actual: "open this dish" },
    { gibberish: "ask cue sing aim", actual: "excusing him" },
    { gibberish: "letch itch rave", actual: "electric wave" },
    { gibberish: "doe fan chew", actual: "don't you" },
    { gibberish: "aim lawn gloat", actual: "I'm long gone" },
    { gibberish: "hike and dew hit", actual: "I can do it" },
    { gibberish: "diz coast ask guys", actual: "disco stars guide" },
    { gibberish: "aim nor mall dune", actual: "I'm normal dude" },
    { gibberish: "tray knit awe fur", actual: "train it over" },
    { gibberish: "whoa churn learn ink", actual: "watch and learning" },
    { gibberish: "none off us is", actual: "none of us is" },
    { gibberish: "aim nap pull gist", actual: "an apologist" },
    { gibberish: "mud eek hoed", actual: "muddy code" },
    { gibberish: "four gust aim itch", actual: "forget image" },
    { gibberish: "drum lick yew rate", actual: "dramatic curate" },
    { gibberish: "yo nigh ted stay its", actual: "United States" },
    { gibberish: "fee link pew lure", actual: "feeling pure" },
    { gibberish: "know bud he cars", actual: "nobody cares" },
    { gibberish: "glow her he port", actual: "glory report" },
    { gibberish: "aim hut ha hush in", actual: "a modest ambition" },
    { gibberish: "hippy urd aim", actual: "a pure dream" },
    { gibberish: "beard owe fit ink", actual: "weird overthinking" },
    { gibberish: "tint hush ape", actual: "into shape" },
    { gibberish: "hash hoop ink star", actual: "a shopping store" },
    { gibberish: "grape flee tin", actual: "grapefruit tea" },
    { gibberish: "jaw bun mess edge", actual: "job message" },
    { gibberish: "hat yew fee el", actual: "how do you feel" },
    { gibberish: "say fern hex stance", actual: "safe and existence" },
    { gibberish: "no win tent shun", actual: "no intention" },
    { gibberish: "dwell hey hush in", actual: "the latest trend" },
    { gibberish: "goat off yawn", actual: "go to fawn" },
    { gibberish: "chalks ink bless", actual: "shocking bliss" },
    { gibberish: "aim peek lure aim", actual: "a peculiar aim" },
    { gibberish: "whey tin lisp in", actual: "wait and listen" },
    { gibberish: "know hun leap heaps", actual: "no one believes" },
    { gibberish: "sane sighed inn", actual: "same side in" },
    { gibberish: "brake hay knees", actual: "break a nice" },
    { gibberish: "so fare is seek", actual: "so far as I see" },
    { gibberish: "aim blew bait", actual: "a blue plate" },
    { gibberish: "free kin awe sum", actual: "freaking awesome" },
    { gibberish: "hope hint ass", actual: "open task" },
    { gibberish: "slit half urn ace", actual: "slept after a nice" },
    { gibberish: "kit fin tray shin", actual: "gifted creation" },
    { gibberish: "cheese ache win", actual: "she’s a queen" },
    { gibberish: "pay curl itch in", actual: "paper legend" },
    { gibberish: "awe way sum one", actual: "always someone" },
    { gibberish: "ink grew dent owl", actual: "incredibly dull" },
    { gibberish: "aim fringe stow rye", actual: "a French story" },
    { gibberish: "ton heel ife", actual: "tiny life" },
    { gibberish: "win hurt ash in", actual: "winter fashion" },
    { gibberish: "yak ace okay", actual: "yeah, it's okay" },
    { gibberish: "dew nut hiss tape", actual: "do not hesitate" },
    { gibberish: "aim verse hint", actual: "a version" },
    { gibberish: "wake aim hinge", actual: "weekend binge" },
    { gibberish: "fee loan gloat", actual: "feel on cloud" }
];
